### HTTP Requests

### Set values for LAT and LONG
@LAT = 37.3614
@LON = -118.7366

### Current Weather
GET http://localhost:3000/current-weather?lat={{LAT}}&lon={{LON}} HTTP/1.1

### 5 Day Forecast
GET http://localhost:3000/forecast-weather?lat={{LAT}}&lon={{LON}} HTTP/1.1