### HTTP Requests

### Set values for LAT and LONG
@LAT = 37.3614
@LON = -118.7366

@PORT = 3000

### Current Weather
GET http://localhost:{{PORT}}/current-weather?lat={{LAT}}&lon={{LON}} HTTP/1.1

### 5 Day Forecast
GET http://localhost:{{PORT}}/forecast-weather?lat={{LAT}}&lon={{LON}} HTTP/1.1